# -*- coding: utf-8 -*-
"""Practical 5 Decision Tree ALGO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12SoEk81ioU-54-756vQzZqlN8zhjU5oD
"""

import pandas as pd
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.preprocessing import LabelEncoder

data = {
     'Alt': ['Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes'],
     'Bar': ['No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No'],
     'Fri': ['No', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes'],
     'Hun': ['Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes'],
     'Pat': ['Some', 'Full', 'Some', 'Full', 'Full', 'Some', 'None', 'Some', 'Full', 'Full', 'None', 'Full'],
     'Price': ['$', '$', '$', '$', '$$', '$$', '$', '$$', '$', '$$', '$', '$$'],
     'Rain': ['No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No'],
     'Res': ['Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No'],
     'Type': ['French', 'Thai', 'Burger', 'Thai', 'French', 'Italian', 'Burger', 'Thai', 'Burger', 'Italian', 'Thai', 'Burger'],
     'Est': ['0-10', '30-60', '0-10', '10-30', '0-10', '>60', '0-10', '0-10, 10-30', '0-10', '0-10', '0-10', '30-60'],
     'WillWait': ['Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes']
}


df = pd.DataFrame(data)

le = LabelEncoder()

for column in df.columns:
    df[column] = le.fit_transform(df[column])

X = df.drop('WillWait', axis=1)


y = df['WillWait']

clf = DecisionTreeClassifier()
clf.fit(X, y)

export_graphviz(clf, out_file='tree.dot', feature_names=X.columns)

print("Decision tree has been exported to 'tree.dot'.")